### ISSUE TITLE
Failed to activate the console-panel package

### ISSUE THREAD

**Issue by myzen2** [spark/console-panel#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [console-panel](https://github.com/spark/console-panel) package, v0.2.0

### Stack Trace

Failed to activate the console-panel package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\celin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\celin\.atom\packages\console-panel\node_modules\event-kit\node_modules\grim\node_modules\emissary\node_modules\underscore-plus\lib\underscore-plus.js:5:7)
    at Object.<anonymous> (C:\Users\celin\.atom\packages\console-panel\node_modules\event-kit\node_modules\grim\node_modules\emissary\node_modules\underscore-plus\lib\underscore-plus.js:522:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\celin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\celin\.atom\packages\console-panel\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\behavior.js:7:13)
    at Object.<anonymous> (C:\Users\celin\.atom\packages\console-panel\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\behavior.js:120:4)
    at Module._compile (module.js:428:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "code-dark-ui",
      "tubster-syntax"
    ],
    "projectHome": "c:\\sites",
    "disabledPackages": [
      "icon-fonts",
      "seti-icons",
      "file-icons",
      "file-icon-supplement",
      "envygeeks-file-icons",
      "semantic-ui"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-fix-path, v0.1.0
Atom-Hack, v6.1.5
atom-javascript-console-snippets, v0.10.0
Atom-Syntax-highlighting-for-Sass, v0.5.0
autoclose-html, v0.19.0
autocomplete-bibtex, v0.6.1
autocomplete-emojis, v2.2.2
autocomplete-glsl, v0.2.3
autocomplete-hack, v2.1.0
autocomplete-html-entities, v0.1.0
autocomplete-kdb-q, v0.4.1
autocomplete-modules, v1.3.0
autocomplete-motion, v2.1.0
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
code-dark-ui, v0.4.1
color-picker, v2.0.13
console-panel, v0.2.0
default-language, v0.2.0
emmet, v2.3.13
enhanced-package-list, v1.0.3
file-type-icons, v0.7.3
hex, v0.6.2
html-entities, v0.4.0
language-b-html, v1.0.0
language-hack, v0.1.1
lg-silverstripe, v0.1.0
linter, v1.9.0
linter-erb, v0.1.1
linter-rails-best-practices, v0.2.2
linter-xo, v0.8.0
minimap, v4.15.0
package-switch, v0.5.0
pigments, v0.18.0
rails-i18n, v0.1.3
remote-edit, v1.8.21
ruby-syntax-replacer, v0.5.1
Sass-Syntax-Highlight, v0.1.1
set-syntax, v0.3.0
sublime-word-navigation, v0.1.2
tab-numbers, v0.3.0
terminal-panel, v1.14.1
terminal-plus, v0.12.1
terminal-status, v1.6.8
toolbar-iconshortcuts, v1.0.0
tree-view-breadcrumb, v0.7.1
tree-view-git-modified, v0.5.12
tubster-syntax, v0.16.2
unfancy-file-icons, v0.1.2

# Dev
No dev packages
```

**Comment by matthewpucc** [comment]
[Enter steps to reproduce:]

1. Clean install of atom
2. Install console-panel
3. On activation of package error, is shown

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [console-panel](https://github.com/spark/console-panel) package 0.2.1


### Stack Trace

Failed to activate the console-panel package

```
At Cannot find module './scroll-view'

Error: Cannot find module './scroll-view'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/Downloads/Atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/console-panel/node_modules/atom-space-pen-views/lib/main.js:20:24)
    at /packages/console-panel/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/console-panel/lib/console-view.coffee:7:10)
    at /packages/console-panel/lib/console-view.coffee:159:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/console-panel/lib/console.coffee:4:17)
    at /packages/console-panel/lib/console.coffee:43:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  3x -2:58 core:backspace (input.hidden-input)
     -2:51.1.0 core:confirm (input.hidden-input)
  5x -2:31 core:backspace (input.hidden-input)
     -2:28.4.0 core:confirm (input.hidden-input)
     -1:25.2.0 core:backspace (input.hidden-input)
  2x -1:23.3.0 core:move-left (input.hidden-input)
     -1:22.8.0 core:backspace (input.hidden-input)
     -1:21.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
console-panel 0.2.1 
```

**Comment by suda** [comment]
Can you try reinstalling the package and rebuilding module cache (with `apm rebuild-module-cache`)? It seems that the package wasn't installed correctly and the dependencies are missing
