### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

### ISSUE THREAD

**Issue by idleberg** [spark/console-panel#5]
[Enter steps to reproduce below:]

I'm not sure if it's my incapacity or whether your service is causing the issue. I was trying to use `console-panel` with `spawn` and run into the error shown below.

Minimal example to reproduce this:

```coffee
cmd = spawn "osascript", [file]

@consolePanel.toggle
@consolePanel.log("This works")

makensis.stderr.on 'data', ( data ) =>
    @consolePanel.error("This doesn't work")
```

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [console-panel](https://github.com/spark/console-panel) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

```
At /Users/somebody/.atom/packages/console-panel/node_modules/jquery/dist/jquery.js:1430

TypeError: Cannot read property 'ownerDocument' of undefined
    at Function.Sizzle.contains (/Users/somebody/.atom/packages/console-panel/node_modules/jquery/dist/jquery.js:1430:16)
    at Function.buildFragment (/Users/somebody/.atom/packages/console-panel/node_modules/jquery/dist/jquery.js:5147:22)
    at jQuery.domManip (/Users/somebody/.atom/packages/console-panel/node_modules/jquery/dist/jquery.js:5387:22)
    at jQuery.append (/Users/somebody/.atom/packages/console-panel/node_modules/jquery/dist/jquery.js:5218:15)
    at ConsoleView.module.exports.ConsoleView.log (/Users/somebody/.atom/packages/console-panel/lib/console-view.coffee:49:15)
    at ConsoleManager.module.exports.ConsoleManager.log (/Users/somebody/.atom/packages/console-panel/lib/console-manager.coffee:19:10)
    at Socket.<anonymous> (/Users/somebody/.atom/packages/language-nsis/lib/main.coffee:95:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -0:01.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)

**Comment by suda** [comment]
Hmm I tried this (ES6 version):

```
    this.consolePanel.toggle();
    this.consolePanel.log('This works');

    let cmd = spawn('whoami')
    cmd.stdout.on('data', (data) => {
      this.consolePanel.error(data.toString().trim())
    });
```
And it does work. Are you using the exact example you posted? Because if you would do `consolePanel.error(data)` (without casting to String), console panel would try to add the `data` (which I think is a `Buffer`) to DOM and it might crash in the way you specified.

**Comment by idleberg** [comment]
`toString()` did the trick, thanks!
